CREATE OR REPLACE FORCE VIEW EDFIDATA.V_DISTRICT AS
SELECT ORG_SID AS DISTRICT_SID
,ORG_NAME||'('||org_cdn||')' AS DISTRICT_NAME
,ACTIVE
,ORG_TYPE
,ORG_CDN
FROM R10INTDATA.ORG_DIM;
grant select on EDFIDATA.V_DISTRICT to EDFIAPP;


