create or replace force view edfidata.v_district_tsi2_data as
select "LINE_NUMBER","TEST_START","LAST_NAME","FIRST_NAME","MIDDLE_INITIAL","STUDENT_ID",SUPPLEMENTAL_ID,"BIRTH_DATE","SITE_ID","INST_ID","TSI2_MATH_READINESS","TSI2_MATH_DIAGNOSTIC","TSI2_ELAR_READINESS","TSI2_ELAR_DIAGNOSTIC","TSI2_ELAR_ESSAY","DISTRICT_ID","FILE_NAME","LOADED_DATE" from DISTRICT_TSI2_DATA;

