create or replace force view edfidata.v_district_tsi_data as
select "LINE_NUMBER","TEST_START","LAST_NAME","FIRST_NAME","MIDDLE_INITIAL","STUDENT_ID","BIRTH_DATE","SITE_ID","INST_ID","TSI_MATHEMATICS_PLACEMENT","TSI_READING_PLACEMENT","TSI_WRITING_PLACEMENT","TSI_WRITEPLACER","ABE_MATHEMATICS_DIAGNOSTICS","ABE_WRITING_DIAGNOSTICS","ABE_READING_DIAGNOSTICS","DISTRICT_ID","FILE_NAME","LOADED_DATE" from edfidata.district_tsi_data;

